### ISSUE TITLE
[Moved]Release date

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-bus#3]
From @jangalinski 
I am waiting for the bus release to adopt my project. Although core is out for some weeks now, bus is still snapshot. What are your plans?

**Comment by jangalinski** [comment]
Since this repo is labeled "legacy" ... is it safe to assume that the eventbus project is dead? In that case I would stop waiting and refactor my app ...

**Comment by gs-spadmanabhan** [comment]
Will there be any enhancements in this project with respect to supporting reactor 3 release?

**Comment by achmadns** [comment]
EventBus was a love at first sight just when I tried to create a generic pub sub mechanism in Swing. I use it extensively as "in memory message broker" which allows me to do multi thread communication with ease and efficient. I do hope this project still has a future or alternative. Many thanks for providing this solution.
